[project]
name = "ctts"
version = "0.1.0"
description = "Compare different text-to-speech providers"
readme = "README.md"
authors = [
    { name = "Dave Savostyanov", email = "ds@artifactory.ai" }
]
requires-python = ">=3.11.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
